version: '3'
services:
  node:
    command: npm start
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./backend/:/usr/src/app/
  mongo:
    restart: always
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: