version: '3'
services:
  backend:
    command: npm start
    restart: always
    build:
      context: .
      dockerfile: Back.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend/:/usr/src/app/
  frontend:
    command: npm start
    restart: always
    build:
      context: .
      dockerfile: Front.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/src/app/
  mongo:
    restart: always
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  mongo_seed:
    image: mongo:3.2.6
    links:
      - mongo
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh
volumes:
 mongodb: